// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Character struct {
	ID          uuid.UUID
	Name        string
	ClassLevels json.RawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      uuid.UUID
}

type CharactersSpell struct {
	SpellID int32
	CharID  uuid.UUID
}

type Class struct {
	ID    int32
	Index string
	Name  string
	Url   sql.NullString
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.NullUUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Spell struct {
	ID            int32
	Index         string
	Name          string
	Range         sql.NullString
	Material      sql.NullString
	Ritual        sql.NullBool
	Duration      sql.NullString
	Concentration sql.NullBool
	CastingTime   sql.NullString
	Level         sql.NullInt32
	AttackType    sql.NullString
	School        pqtype.NullRawMessage
	Desc          []string
	HigherLevel   []string
	Components    []string
	Damage        pqtype.NullRawMessage
	Url           string
	UpdatedAt     sql.NullTime
}

type SpellClass struct {
	SpellID int32
	ClassID int32
}

type SpellSlot struct {
	CasterType  string
	CasterLevel int32
	Slots       json.RawMessage
}

type SpellSubclass struct {
	SpellID    int32
	SubclassID int32
}

type Subclass struct {
	ID    int32
	Index string
	Name  string
	Url   sql.NullString
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Role           string
}
