// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addClass = `-- name: AddClass :one
INSERT INTO classes (index, name, url)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, index, name, url
`

type AddClassParams struct {
	Index string
	Name  string
	Url   sql.NullString
}

func (q *Queries) AddClass(ctx context.Context, arg AddClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, addClass, arg.Index, arg.Name, arg.Url)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Index,
		&i.Name,
		&i.Url,
	)
	return i, err
}

const addSpellClass = `-- name: AddSpellClass :one
INSERT INTO spell_classes (spell_id, class_id)
VALUES (
    $1,
    $2
)
RETURNING spell_id, class_id
`

type AddSpellClassParams struct {
	SpellID int32
	ClassID int32
}

func (q *Queries) AddSpellClass(ctx context.Context, arg AddSpellClassParams) (SpellClass, error) {
	row := q.db.QueryRowContext(ctx, addSpellClass, arg.SpellID, arg.ClassID)
	var i SpellClass
	err := row.Scan(&i.SpellID, &i.ClassID)
	return i, err
}

const addSpellSlots = `-- name: AddSpellSlots :one
INSERT INTO spell_slots (caster_type, caster_level, slots)
VALUES (
    $1,
    $2,
    $3
)
RETURNING caster_type, caster_level, slots
`

type AddSpellSlotsParams struct {
	CasterType  string
	CasterLevel int32
	Slots       json.RawMessage
}

func (q *Queries) AddSpellSlots(ctx context.Context, arg AddSpellSlotsParams) (SpellSlot, error) {
	row := q.db.QueryRowContext(ctx, addSpellSlots, arg.CasterType, arg.CasterLevel, arg.Slots)
	var i SpellSlot
	err := row.Scan(&i.CasterType, &i.CasterLevel, &i.Slots)
	return i, err
}

const addSpellSubclass = `-- name: AddSpellSubclass :one
INSERT INTO spell_subclasses (spell_id, subclass_id)
VALUES (
    $1,
    $2
)
RETURNING spell_id, subclass_id
`

type AddSpellSubclassParams struct {
	SpellID    int32
	SubclassID int32
}

func (q *Queries) AddSpellSubclass(ctx context.Context, arg AddSpellSubclassParams) (SpellSubclass, error) {
	row := q.db.QueryRowContext(ctx, addSpellSubclass, arg.SpellID, arg.SubclassID)
	var i SpellSubclass
	err := row.Scan(&i.SpellID, &i.SubclassID)
	return i, err
}

const addSubclass = `-- name: AddSubclass :one
INSERT INTO subclasses (index, name, url)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, index, name, url
`

type AddSubclassParams struct {
	Index string
	Name  string
	Url   sql.NullString
}

func (q *Queries) AddSubclass(ctx context.Context, arg AddSubclassParams) (Subclass, error) {
	row := q.db.QueryRowContext(ctx, addSubclass, arg.Index, arg.Name, arg.Url)
	var i Subclass
	err := row.Scan(
		&i.ID,
		&i.Index,
		&i.Name,
		&i.Url,
	)
	return i, err
}

const createSpell = `-- name: CreateSpell :one
INSERT INTO spells (index, name, range, material, ritual, duration, concentration, casting_time, level, attack_type, school, "desc", higher_level, components, damage, url, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    NOW()
)
RETURNING id, index, name, range, material, ritual, duration, concentration, casting_time, level, attack_type, school, "desc", higher_level, components, damage, url, updated_at
`

type CreateSpellParams struct {
	Index         string
	Name          string
	Range         sql.NullString
	Material      sql.NullString
	Ritual        sql.NullBool
	Duration      sql.NullString
	Concentration sql.NullBool
	CastingTime   sql.NullString
	Level         sql.NullInt32
	AttackType    sql.NullString
	School        pqtype.NullRawMessage
	Desc          []string
	HigherLevel   []string
	Components    []string
	Damage        pqtype.NullRawMessage
	Url           string
}

func (q *Queries) CreateSpell(ctx context.Context, arg CreateSpellParams) (Spell, error) {
	row := q.db.QueryRowContext(ctx, createSpell,
		arg.Index,
		arg.Name,
		arg.Range,
		arg.Material,
		arg.Ritual,
		arg.Duration,
		arg.Concentration,
		arg.CastingTime,
		arg.Level,
		arg.AttackType,
		arg.School,
		pq.Array(arg.Desc),
		pq.Array(arg.HigherLevel),
		pq.Array(arg.Components),
		arg.Damage,
		arg.Url,
	)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.Index,
		&i.Name,
		&i.Range,
		&i.Material,
		&i.Ritual,
		&i.Duration,
		&i.Concentration,
		&i.CastingTime,
		&i.Level,
		&i.AttackType,
		&i.School,
		pq.Array(&i.Desc),
		pq.Array(&i.HigherLevel),
		pq.Array(&i.Components),
		&i.Damage,
		&i.Url,
		&i.UpdatedAt,
	)
	return i, err
}
