// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spellcalls.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const getAllSpells = `-- name: GetAllSpells :many
SELECT "index", name, ritual, concentration, level, url
FROM spells
`

type GetAllSpellsRow struct {
	Index         string
	Name          string
	Ritual        sql.NullBool
	Concentration sql.NullBool
	Level         sql.NullInt32
	Url           string
}

func (q *Queries) GetAllSpells(ctx context.Context) ([]GetAllSpellsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSpells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSpellsRow
	for rows.Next() {
		var i GetAllSpellsRow
		if err := rows.Scan(
			&i.Index,
			&i.Name,
			&i.Ritual,
			&i.Concentration,
			&i.Level,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpell = `-- name: GetSpell :one
SELECT "index", name, range, material, ritual, duration, concentration, casting_time, "level", attack_type, school, "desc", higher_level, components, damage
FROM spells
WHERE "index" = $1
`

type GetSpellRow struct {
	Index         string
	Name          string
	Range         sql.NullString
	Material      sql.NullString
	Ritual        sql.NullBool
	Duration      sql.NullString
	Concentration sql.NullBool
	CastingTime   sql.NullString
	Level         sql.NullInt32
	AttackType    sql.NullString
	School        pqtype.NullRawMessage
	Desc          []string
	HigherLevel   []string
	Components    []string
	Damage        pqtype.NullRawMessage
}

func (q *Queries) GetSpell(ctx context.Context, index string) (GetSpellRow, error) {
	row := q.db.QueryRowContext(ctx, getSpell, index)
	var i GetSpellRow
	err := row.Scan(
		&i.Index,
		&i.Name,
		&i.Range,
		&i.Material,
		&i.Ritual,
		&i.Duration,
		&i.Concentration,
		&i.CastingTime,
		&i.Level,
		&i.AttackType,
		&i.School,
		pq.Array(&i.Desc),
		pq.Array(&i.HigherLevel),
		pq.Array(&i.Components),
		&i.Damage,
	)
	return i, err
}

const getSpellID = `-- name: GetSpellID :one
SELECT id
FROM spells
WHERE "index" = $1
`

func (q *Queries) GetSpellID(ctx context.Context, index string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getSpellID, index)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getSpellsClass = `-- name: GetSpellsClass :many
SELECT s."index", s.name, s.ritual, s.concentration, s.level, s.url
FROM spells AS s
JOIN spell_classes AS sc ON sc.spell_id = s.id
JOIN classes AS c ON c.id = sc.class_id
WHERE c."index" = $1
ORDER BY s.level, s.name
`

type GetSpellsClassRow struct {
	Index         string
	Name          string
	Ritual        sql.NullBool
	Concentration sql.NullBool
	Level         sql.NullInt32
	Url           string
}

func (q *Queries) GetSpellsClass(ctx context.Context, index string) ([]GetSpellsClassRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsClass, index)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsClassRow
	for rows.Next() {
		var i GetSpellsClassRow
		if err := rows.Scan(
			&i.Index,
			&i.Name,
			&i.Ritual,
			&i.Concentration,
			&i.Level,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsConcentration = `-- name: GetSpellsConcentration :many
SELECT "index", name, level, url
FROM spells
WHERE concentration = 't'
ORDER BY level, name
`

type GetSpellsConcentrationRow struct {
	Index string
	Name  string
	Level sql.NullInt32
	Url   string
}

func (q *Queries) GetSpellsConcentration(ctx context.Context) ([]GetSpellsConcentrationRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsConcentration)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsConcentrationRow
	for rows.Next() {
		var i GetSpellsConcentrationRow
		if err := rows.Scan(
			&i.Index,
			&i.Name,
			&i.Level,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsLevel = `-- name: GetSpellsLevel :many
SELECT "index", name, level, url
FROM spells
WHERE "level" = $1
`

type GetSpellsLevelRow struct {
	Index string
	Name  string
	Level sql.NullInt32
	Url   string
}

func (q *Queries) GetSpellsLevel(ctx context.Context, level sql.NullInt32) ([]GetSpellsLevelRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsLevelRow
	for rows.Next() {
		var i GetSpellsLevelRow
		if err := rows.Scan(
			&i.Index,
			&i.Name,
			&i.Level,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsRitual = `-- name: GetSpellsRitual :many
SELECT "index", name, level, url
FROM spells
WHERE ritual = 't'
ORDER BY level, name
`

type GetSpellsRitualRow struct {
	Index string
	Name  string
	Level sql.NullInt32
	Url   string
}

func (q *Queries) GetSpellsRitual(ctx context.Context) ([]GetSpellsRitualRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsRitual)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsRitualRow
	for rows.Next() {
		var i GetSpellsRitualRow
		if err := rows.Scan(
			&i.Index,
			&i.Name,
			&i.Level,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsSubclass = `-- name: GetSpellsSubclass :many
SELECT s."index", s.name, s.ritual, s.concentration, s.level, s.url
FROM spells AS s
JOIN spell_subclasses AS ss ON ss.spell_id = s.id
JOIN subclasses AS sc ON sc.id = ss.subclass_id
WHERE sc."index" = $1
ORDER BY s.level, s.name
`

type GetSpellsSubclassRow struct {
	Index         string
	Name          string
	Ritual        sql.NullBool
	Concentration sql.NullBool
	Level         sql.NullInt32
	Url           string
}

func (q *Queries) GetSpellsSubclass(ctx context.Context, index string) ([]GetSpellsSubclassRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsSubclass, index)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsSubclassRow
	for rows.Next() {
		var i GetSpellsSubclassRow
		if err := rows.Scan(
			&i.Index,
			&i.Name,
			&i.Ritual,
			&i.Concentration,
			&i.Level,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpell = `-- name: UpdateSpell :one
UPDATE spells
SET name = $1, range = $2, material = $3, ritual = $4, duration = $5, concentration = $6, casting_time = $7, "level" = $8, attack_type = $9, school = $10, "desc" = $11, higher_level = $12, components = $13, damage = $14, updated_at = NOW()
WHERE "index" =  $15
RETURNING "index", name, range, material, ritual, duration, concentration, casting_time, "level", attack_type, school, "desc", higher_level, components, damage
`

type UpdateSpellParams struct {
	Name          string
	Range         sql.NullString
	Material      sql.NullString
	Ritual        sql.NullBool
	Duration      sql.NullString
	Concentration sql.NullBool
	CastingTime   sql.NullString
	Level         sql.NullInt32
	AttackType    sql.NullString
	School        pqtype.NullRawMessage
	Desc          []string
	HigherLevel   []string
	Components    []string
	Damage        pqtype.NullRawMessage
	Index         string
}

type UpdateSpellRow struct {
	Index         string
	Name          string
	Range         sql.NullString
	Material      sql.NullString
	Ritual        sql.NullBool
	Duration      sql.NullString
	Concentration sql.NullBool
	CastingTime   sql.NullString
	Level         sql.NullInt32
	AttackType    sql.NullString
	School        pqtype.NullRawMessage
	Desc          []string
	HigherLevel   []string
	Components    []string
	Damage        pqtype.NullRawMessage
}

func (q *Queries) UpdateSpell(ctx context.Context, arg UpdateSpellParams) (UpdateSpellRow, error) {
	row := q.db.QueryRowContext(ctx, updateSpell,
		arg.Name,
		arg.Range,
		arg.Material,
		arg.Ritual,
		arg.Duration,
		arg.Concentration,
		arg.CastingTime,
		arg.Level,
		arg.AttackType,
		arg.School,
		pq.Array(arg.Desc),
		pq.Array(arg.HigherLevel),
		pq.Array(arg.Components),
		arg.Damage,
		arg.Index,
	)
	var i UpdateSpellRow
	err := row.Scan(
		&i.Index,
		&i.Name,
		&i.Range,
		&i.Material,
		&i.Ritual,
		&i.Duration,
		&i.Concentration,
		&i.CastingTime,
		&i.Level,
		&i.AttackType,
		&i.School,
		pq.Array(&i.Desc),
		pq.Array(&i.HigherLevel),
		pq.Array(&i.Components),
		&i.Damage,
	)
	return i, err
}
